### ISSUE TITLE
Source code for the document generation

### ISSUE THREAD

**Issue by lvcargnini** [chipsalliance/AIB-specification#1]
Hello,

Where is the main source of the document? The .docx/.tex file so someone can propose an alteration and submit it as a patch in a merge request.

I saw in the document the usage of Master/Slave, keywords despite being traditionally used, due to events in 2020, companies like ARM and other specifications have been replacing it by additional terms, e.g.,  Controller/Agents, Controller/nodes. So, how could someone submit such amendments without the main document?

**Comment by dkehlet** [comment]
Hello Luis, please see the AIB 2.0 specification. The two sides are now labeled as Leader and Follower. The 1.2 spec is now obsolete. Should we remove the 1.2 spec?

If you would like to contribute to the specification, please sign and send the OWFa 1.0 license agreement in this folder.

Dave

**Comment by dkehlet** [comment]
Fixed in 2.0 Draft3.

**Comment by lvcargnini** [comment]
Hi @dkehlet Dave, sorry the message was buried in my inbox. No, I haven't seen on 2.0 yet, will look into it. Thank you.
