### ISSUE TITLE
Minor typo in spec

### ISSUE THREAD

**Issue by jarchambeault** [chipsalliance/AIB-specification#18]
There is an obvious typo in AIB spec. On draft 5 it is in page 20, table 3 but it has been in the spec since a least draft3.

The table shows the data rates for various generations on SDR/DDR. The Gen 1 SDR shows 500Gbps and while I applaud the idea we can run at 1/2Tbps, it is obviously intended to be 500Mbps.

**Comment by dkehlet** [comment]
Fixed in DRAFT6
