### ISSUE TITLE
Errors in Bump-Table Exemplars AIB 1.2 Spec

### ISSUE THREAD

**Issue by b-sampson** [chipsalliance/AIB-specification#43]
In the AIB Specification 1.2, it appears to me there's an error in Table 36 Bump-Table Exemplar (AIB Base, Balanced) with the calculation of x and y based on n, leading to impossible bump assignments.

Take for example, AIB0 in Table 36 and Table 43. It's clear that from comparing these two, n must be equal to 20. However, calculating x now based on Table 36, we get x = 20/2 - 10 = 0. Then evaluating x through the table leads to nonsensical bump assignments such as ns_fwd_clk and TX[n-2] are both AIB0.

![aib_1v2_table_36](https://user-images.githubusercontent.com/48960200/137743368-77fb49c0-62c1-4f1c-9fe7-2a9bbe4c42a5.png)
![aib_1v2_table_43](https://user-images.githubusercontent.com/48960200/137743373-0f6d6127-4720-4848-a43e-612a3bc5d7d6.png)

**Comment by b-sampson** [comment]
Same problem with Table 39 and Table 46 for AIB Plus Balanced. This time x is negative, x = 20/2 - 12 = -2

**Comment by b-sampson** [comment]
It seems that there are two ways to resolve this depending upon what the definition of ``n`` is.

1. If n is the total number of bumps per AIB channel (n = TX + RX), then the equations for x and y should be left the same but the Bump Name columns in the table, should replace every n with a n/2 (i.e. TX[n - 1] -> TX[n/2 -1])
2. If n is the max of TX bumps or RX bumps per AIB channel (n = MAX(TX,RX)), then the Bump Name columns can be left alone but the x and y equations should be updated to replace all n with 2n. So then, as an example for the AIB Plus Balanced, x = n -12 and y = 2n+20

**Comment by b-sampson** [comment]
I checked the All-Tx and All-Rx tables for both AIB Base and AIB Plus and those appear to be correct to me so no change needed there

**Comment by dkehlet** [comment]
Erroneous 1.2 Table,                Corrected 2.0 Table
36,                                            40
39,                                            43

**Comment by dkehlet** [comment]
Hello Ben, apologies for the error.  This was fixed in the 2.0 specification. This was recorded as github issue #20 under chipsalliance/aib-phy-hardware, but strangely gone now. It is recorded in the revision history of the 2.0 spec. Sorry you had to rediscover it.

**Comment by dkehlet** [comment]
Refer to 2.0 specification for the fix.
