### ISSUE TITLE
Standard AIB to AIB Legacy not fully defined?

### ISSUE THREAD

**Issue by b-sampson** [chipsalliance/AIB-specification#44]
It's clear from the AIB Spec v2.0 that the AUX channel from the Leader should be connected to the AUX channel on the Follower as described in Table 46 AIB AUX Signal Bump Table.

But it's not clear to me how you might connect the AUX channel for a chiplet that implements the Alternate Channel Bump Map (what I am used to being called "AIB Legacy") to an 4-bump AUX channel on the AIB 1.2 or 2.0 interfaces. I'm used to AIB Legacy interfaces that have 96 bumps (just like the non-AUX AIB channels for AIB Legacy) but it's not clear if or which bumps would need to be connected to the 4-bump AUX channel in an AIB 1.2 or 2.0 implementation.

I feel that Section 6.6 on Alternate Bump Maps would be the right place to clarify this but it currently does not mention how to handle the AIB AUX channel for alternate bump maps (AIB Legacy). Here's what I believe should be addressed:
* Should the AIB AUX channel be used for a chiplet that implements the Alternate Bump Map?
* If yes to the question above, how should it be implemented?
* If no to the first question, what should be done with the unconnected AIB AUX signals on the AIB 1.2/2.0 and AIB Legacy sides?

**Comment by dkehlet** [comment]
We found that the 4-bump AUX channel is awkward to implement. Rather, we've taken the approach of Figure 10 in the "AIB Usage Note" at
https://github.com/chipsalliance/aib-phy-hardware/blob/master/docs/AIB_Usage_Note_v1_2_3.pdf
The two signals involved, device_detect and power_on_reset need to be implemented as shown in the 2.0 spec Figure 40 (which can be simplified if you are not implementing dual mode).

    Q: Should the AUB AUX channel be used...
Yes, considering that "AUX Channel" is just these two signals and the best way to implement them is using standard C4 bumps.

I will devise a more proper response ASAP. If how to go forward right now is not clear please let me know.

**Comment by b-sampson** [comment]
The AIB usage note really has the information I'm looking for in Table 6 AUX Channel Bump Table with IO Configuration as Used by AIB Open Source. 

Let's see if I understand what you're saying then. Let's say the Leader chiplet is Stratix 10-like (96 bumps in AUX channel), the follower chiplet is AIB 2.0, and device_detect/power_on_reset are routed through microbumps (not C4 bumps). 

Would this then be the correct routing for the used AUX signals?

| Leader Bump ID | Leader Bump Name | Leader AUX IO | Follower AUX IO | Follower Bump ID | Follower Bump Name |
|----------------|------------------|---------------|-----------------|--------------------|------------------|
| AIB74          | device_detect    | out           | in              | AIBX3              | device_detect    |
| AIB75          | device_detect    | out           | in              | AIBX2              | device_detect    |
| AIB85          | power_on_reset   | in            | out             | AIBX1              | power_on_reset   |
| AIB87          | power_on_reset   | in            | out             | AIBX0              | power_on_reset   |

**Comment by dkehlet** [comment]
Leader Bump IDs and signal names match AIB Usage Note Table 6, verified with internal source now.
Leader / Follower in and out match Table 6, also AIB Spec.
Your table "Follower Bump Name" should be "Follower Bump ID." Check also adjacent column.
See also Usage Note section 7.2.2.
Stratix 10 follower AUX needed some inputs connected to VSSP. Yu need to examine your own Leader to see the appropriate connection to the other microbumps in the AUX channel.

**Comment by dkehlet** [comment]
And if it's not too late for your Leader, I recommend a no-microbump AUX.

**Comment by b-sampson** [comment]
> Your table "Follower Bump Name" should be "Follower Bump ID." Check also adjacent column.

Yes good catch. I've fixed it now by updating the original comment.

> Stratix 10 follower AUX needed some inputs connected to VSSP. Yu need to examine your own Leader to see the appropriate connection to the other microbumps in the AUX channel.

Understood. That makes sense.

Thank you for the help. For the AIB 2.0 Specification, do you think it's worthwhile to reference this AIB usage note in Section 6.6 Alternate Bump Maps? I don't see a References section in the 2.0 spec but maybe it's not really worth it as the alternate bump maps, in theory, will be phased out over time as new chiplets no longer implement them and instead implement AIB 2.0.

I think with an answer on that - we can close out this issue.

**Comment by dkehlet** [comment]
Closed one year after last comment.
