### ISSUE TITLE
Errata in 2.0 Spec and earlier: Figures 61, 62 titles switched, Table 48 extra signals should be empty

### ISSUE THREAD

**Issue by RI-dittrich** [chipsalliance/AIB-specification#45]
In Spec Revision 2.0.2:

Figure 61: Title should be "Low-Density Bump Map (AIB Base, 20 RX)". Change AIB 28 and 29 to 'unused' to be aligned with Table 49.

Figure 62: Title should be "Low-Density Bump Map (AIB Base, 20 TX)"

**Comment by dkehlet** [comment]
Nice find! Thanks. There are a few problems in this area.
1. Figure 61: Title should be "Low-Density Bump Map (AIB Base, 20 RX)."  See Table 48 to match the spare locations.
2. Figure 62: Title should be "Low-Density Bump Map (AIB Base, 20 TX)."  See Table 49 to match the spare locations.
3. Figure 62: Bumps AIB29 and AIB28 should be labeled "Unused." Note that Table 49 does not have AIB29 or AIB28 defined.
4. Table 48 includes signals at AIB0 and AIB1 that are not part of an RX only interface. AIB0 and AIB1 should be marked "(empty)" in this table. See Tables 42 and 38 that do not include those signals.

These errors exist in the original 1.0 specification.

**Comment by dkehlet** [comment]
Fixed in 2.0.3.
