### ISSUE TITLE
Consider more Specific Bump Specification

### ISSUE THREAD

**Issue by RI-dittrich** [chipsalliance/AIB-specification#46]
From OSAT perspective the bump spacing specifications in Table 25 (Rev 2.0.2) is weak. Since the X1 spacing has no clear minimum with the "shall" criteria it is not possible to optimize an interposter technology for general AIB routing. I think this is a barrier to establish a chiplet-packaging supply chain.

**Comment by dkehlet** [comment]
Hi, thanks for the feedback. Yes, the flexibility in X1 means there could be scenarios where a chiplet might have too fine a bump pitch for a particular interposer technology. However our experience is the opposite: the interposer technology has been more capable than the pitch used on chiplets. Minimizing the chiplet's bump array die area is a strong pressure to reduce cost. A new chiplet, knowing the interposer technology it is targeting, might shrink X1 as small as possible to minimize die area. The interposer can bridge chiplets using different X1 values, as long as the chiplets use spacing the interposer supports. This scenario does occur in projects we're aware of.

**Comment by RI-dittrich** [comment]
Hi, thanks for explanation. Regards
